/* Site config — generated by scripts/sync-config.js (do not edit by hand) */
window.BIGBRAIN_CONFIG = {
  knowledgeUrl: "data/knowledge.json",
  substackUrl: "https://xbigbrainnx.substack.com",
  buyBase: "https://selar.com/m/xbig-brainnx1",
  telegramBotToken: "",
  telegramChatId: ""
};
