#!/usr/bin/env node
/* Writes js/config.js. Telegram keys are NOT written here any more —
   they stay server-side and are read by api/inquiry.js from env
   (Vercel env vars in production, .env locally via `vercel dev`). */
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const configPath = path.join(root, 'js', 'config.js');

const out = `/* Site config — generated by scripts/sync-config.js (do not edit by hand) */
window.BIGBRAIN_CONFIG = {
  knowledgeUrl: "data/knowledge.json",
  substackUrl: "https://xbigbrainnx.substack.com",
  buyBase: "https://selar.com/m/xbig-brainnx1",
  studioUrl: "https://wintechstudio.com",
  templatesUrl: "https://app.wintechstudio.com",
  inquiryEndpoint: "/api/inquiry"
};
`;

fs.writeFileSync(configPath, out);
console.log('Updated js/config.js — Telegram is relayed through /api/inquiry (token stays on the server).');

/* Absolute URLs for og:image / canonical. Runs only in the Vercel build so the
   source files keep the __SITE_URL__ token. SITE_URL env wins (custom domain);
   otherwise Vercel's production URL is used. */
if (process.env.VERCEL) {
  const site = (process.env.SITE_URL || ('https://' + (process.env.VERCEL_PROJECT_PRODUCTION_URL || process.env.VERCEL_URL || ''))).replace(/\/$/, '');
  const glob = require('fs').readdirSync;
  const pages = ['index.html','about.html','no-code.html','mvp.html']
    .concat(glob(path.join(root,'works')).filter(f => f.endsWith('.html')).map(f => 'works/' + f));
  let n = 0;
  pages.forEach(function (rel) {
    const file = path.join(root, rel);
    if (!fs.existsSync(file)) return;
    const html = fs.readFileSync(file, 'utf8');
    if (html.indexOf('__SITE_URL__') === -1) return;
    fs.writeFileSync(file, html.split('__SITE_URL__').join(site)); n++;
  });
  console.log('Set site URL to ' + site + ' in ' + n + ' page(s).');
}
