#!/usr/bin/env node
/* Writes telegram keys into js/config.js from:
   1) process.env (Vercel / CI), or
   2) local .env file
*/
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const envPath = path.join(root, '.env');
const configPath = path.join(root, 'js', 'config.js');

const fileEnv = {};
if (fs.existsSync(envPath)) {
  fs.readFileSync(envPath, 'utf8').split(/\r?\n/).forEach(function (line) {
    line = line.trim();
    if (!line || line.charAt(0) === '#') return;
    var i = line.indexOf('=');
    if (i === -1) return;
    fileEnv[line.slice(0, i).trim()] = line.slice(i + 1).trim();
  });
}

const token = process.env.TELEGRAM_BOT_TOKEN || fileEnv.TELEGRAM_BOT_TOKEN || '';
const chatId = process.env.TELEGRAM_CHAT_ID || fileEnv.TELEGRAM_CHAT_ID || '';

const out = `/* Site config — generated by scripts/sync-config.js (do not edit by hand) */
window.BIGBRAIN_CONFIG = {
  knowledgeUrl: "data/knowledge.json",
  substackUrl: "https://xbigbrainnx.substack.com",
  buyBase: "https://selar.com/m/xbig-brainnx1",
  telegramBotToken: ${JSON.stringify(token)},
  telegramChatId: ${JSON.stringify(chatId)}
};
`;

fs.writeFileSync(configPath, out);

if (token && chatId) {
  console.log('Updated js/config.js — Telegram configured.');
} else {
  console.warn('Updated js/config.js — Telegram keys are still empty.');
  console.warn('Set TELEGRAM_BOT_TOKEN and TELEGRAM_CHAT_ID in .env (local) or Vercel env vars (deploy).');
}
